global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'flask-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['flask-counter:5000']
